### ISSUE TITLE
Space Used not shown

### ISSUE THREAD

**Issue by gl-lamhnguyen** [JZ-SmartThings/SmartThings#1]
Works perfect, but on my rpi I had to change `-f 14` to `-f 15` to be able to display the Space Used from:

`"Space Used" => shell_exec('df -h|grep /dev/root | cut -d \' \' -f 14 | tr -d \'\n\''),`

Awesome work!

**Comment by JZ-SmartThings** [comment]
Very cool, thanks for the feedback! Wondering what size of a card you have. When I plugged in your example above, I got a forward slash which is /dev/root symbolic link :) I think it's because you used something larger than 10GB so that may be our difference. I may use the "last" characters instead of a field delimiter.

Can you please provide the following outputs from these commands?
df -h|grep /dev/root
and this:
df -h|grep /dev/root | tail -c 6 | tr -d ' \/'
EDIT: one more:
df -h|grep /dev/root | awk '{print $(NF-1)}'

Thanks!

**Comment by gl-lamhnguyen** [comment]
Yeah I'm using 32gb card, here are the outputs respectively:

```
/dev/root        14G  3.7G  8.7G  30% /
30%
```

I'm having some issue with my second server (I have 2 running but I could only make it work for 1 of them). Do I need to create another Device Handler for 2nd device?

**Comment by JZ-SmartThings** [comment]
Yes definitely create another device with the same device handler assigned --- remember the device address is changed AUTOMATICALLY on the very first execution. So your IP & port is converted to hex.

Please also try this command for me: df -h|grep /dev/root | awk '{print $(NF-1)}'

**Comment by gl-lamhnguyen** [comment]
This is the event logs (from live logging), I use the same device handler:

![image](https://cloud.githubusercontent.com/assets/14063546/14303095/5fe7e232-fb5c-11e5-9ceb-ca64ce33b6a9.png)

The tiles won't update, it just stays blank.

PS, your cmd outputs `30%`

**Comment by JZ-SmartThings** [comment]
method should be POST not GET

I'm going to go with the AWK/last command I sent you. It's cleanest.

Thanks!

**Comment by gl-lamhnguyen** [comment]
Weird, I also used GET on my 1st server and it worked, anyway I changed to POST, still wouldn't work.

I'm afraid this is network issue, is it possible to use outside IP, for example, I have endpoint at 

```
https://xx.xx.xx.xx:4430/smartthings/httpdevice.php
```

How would I fill the preferences?

**Comment by JZ-SmartThings** [comment]
Just add this to the **URL Path** in preferences: **/smartthings/httpdevice.php**

I'll post the changes we discovered here and close out this issue. Thanks again for the prompt feedback!

**Comment by gl-lamhnguyen** [comment]
Yeah I know that part, but can I use an external IP in `DeviceIP`?

**Comment by JZ-SmartThings** [comment]
Honestly never tested an internet facing IP. Give it a shot, I don't see why the HUBACTION on ST would not respect a public IP.

FYI, just fixed the bug and committed it.

For testing, always try with the web browser first on a desktop. PHP has to succeed and obviously when I'm coding that thing here and there, things break due to syntax, parens, etc. Only then I move onto SmartThings. Looks like you've been around this block, this isn't new :) just wanted to throw it out there.

**Comment by gl-lamhnguyen** [comment]
Thanks, I'll try this when I get home, browsing from an external DNS worked fine, but it might be my 2nd server isn't connect to the same wifi network hence the Hub cannot talk to it internally.

**Comment by JZ-SmartThings** [comment]
I did hear that HUBACTION and the assigned DEVICEID can be "limited" with respect to 10.x.x.x subnet but that's about the only IP limit I've heard on ST forums --- take that as rumor until you can validate that. See this post: https://community.smartthings.com/t/any-documentation-on-physicalgraph-device-hubaction/3117
