### ISSUE TITLE
IR Handling 

### ISSUE THREAD

**Issue by B0R1K** [JZ-SmartThings/SmartThings#10]
Hi 

Thank you for sharing your proj an code,

i was wondering if u shared the code that actually handles "/ir?tv=chandown" request from SmartThing Hub?

Thank you

**Comment by JZ-SmartThings** [comment]
My pleasure!

Yep the TVDevice.groovy file does indeed have channel buttons but you can only use the ST app to control it.

If you mean specifically being able to control the channel via Alexa then I am "kinda" sharing it via the second groovy file called TVvolume.groovy --- basically replace the volume URLs with channel and you would control it by saying ON for chanup and OFF for chandown.

**Comment by B0R1K** [comment]
Thank you for Replying.

What i mean is you are passing "/ir?tv=chandown" to web server,
that i am assuming running on your ESP8266, what does the web server code do? 
is it implementing/wrapping IRremoteESP8266 lib?

Thank you.

**Comment by JZ-SmartThings** [comment]
Yes of course... the "server" in our case Arduino/ESP8266 accepts the HTTP request then it processes IR sequences that you replace in my code. Please read the first post in my SmartThings thread and make sure to visit @casper's initial post where I learned how to DUMP the IR sequence so that you can use that dumped content inside of my code.
