### ISSUE TITLE
Issue with "switch" in parse() return value

### ISSUE THREAD

**Issue by casper-gh** [JZ-SmartThings/SmartThings#3]
So I was trying to use this http://www.smarttiles.click/ to create a dashboard for ST devices, then I found out that my custom switches (HTTP device handlers) doesn't update the status correctly (they always go back to OFF position after refresh).

I emailed their support along with my HTTP device handler and they said:

> You need to issue an Event of Name: "switch" (it is required in the contract of  Capability Switch); otherwise SmartTiles (and any SmartApp using "Switch") will never receive a response to the `subscribe()` method. 
> 
> Attributes in SmartThings are  only  updated via `sendEvent()` (or the implied `sendEvent()` that occurs at the end of `parse()`. 

So I went ahead and edit the groovy code:

```
    case 'mainoff':
        sendEvent(name: "mainswitch", value: "off", isStateChange: true)
        //def result = createEvent(name: "mainswitch", value: "off", isStateChange: true)
        def result = createEvent(name: "switch", value: "off", isStateChange: true)
        return result
    case 'mainon':
        sendEvent(name: "mainswitch", value: "on", isStateChange: true)
        //def result = createEvent(name: "mainswitch", value: "on", isStateChange: true)
        def result = createEvent(name: "switch", value: "on", isStateChange: true)
        return result
```

The commented out is the original code and my new code on next line. Now the switches on dashboard update status correctly. Any thoughts?

**Comment by JZ-SmartThings** [comment]
Dude, nice post on ST forum... very impressive. I ordered the Amazon RF kit and going to try figuring out how you READ the RF info which you obviously later used in the sketch.

FYI, tried your solution and it certainly works... in fact it now makes sense why the tile states are so flaky. I even pulled off the sendEvent and just went with the below, it works... obviously not for the CUSTOM command but for the primary/main switch. Notice below how much I commented out:

```
        case 'mainoff':
            //sendEvent(name: "mainswitch", value: "off", isStateChange: true)
            //def result = createEvent(name: "mainswitch", value: "off", isStateChange: true)
            def result = createEvent(name: "switch", value: "off", isStateChange: true)
            return result
        case 'mainon':
            //sendEvent(name: "mainswitch", value: "on", isStateChange: true)
            //def result = createEvent(name: "mainswitch", value: "on", isStateChange: true)
            def result = createEvent(name: "switch", value: "on", isStateChange: true)
            return result
```

Thanks for bringing this to my attention... I'll change it up for sure!

**Comment by casper-gh** [comment]
That's awesome, I updated the code on mine as well. But actually there was no issue before this at all, from iOS ST native app to Alexa all work perfectly ...until I tried it with SmartTiles dashboard. I don't really understand ST groovy framework so I just play with it 'til it works lol!

I didn't use RF so not sure how to achieve it, hopefully there will be some libraries online. I got lucky and found the library for IR control :smile: 

Let's close this issue then.

**Comment by JZ-SmartThings** [comment]
Yep, mind slipped... I meant IR, not RF :)

**Comment by casper-gh** [comment]
In that case it's simple, that library has some builtin IR devices when you record, but I found that using raw data works bettet, hit me up when you work on that.

Btw there's a flaw with my project, the batteries only last for like 1~2 days, I forgot about the wifi, it consumes lots of power I think. Now I have to hook it up with the micro usb power cord.

Are you planning on using portable power source as well?

**Comment by JZ-SmartThings** [comment]
Thank you, I REALLY appreciate it. It's super-new to me and I'll definitely bug you a time or two, if you don't mind :)

BTW, I swear, this morning I was reading your project post again and checking all of the linked resources and I saw your comment about battery powered (maybe in the video or the text) and I was thinking to myself that this will be the result with the batteries :) but honestly was hoping that you'd prove me wrong because all-wireless is pretty cool but there's no way with the voltage and amps required by the small board. I'm definitely going to be wired. It seems like we have no choice. Having said that, don't toss the battery idea totally out... remote control cars (that I've seen on Youtube & ESP8266) would love to get 2 hours of juice. It has uses for sure.

**Comment by casper-gh** [comment]
Yeah no worries, bug me anytime :)

Regarding the battery issue, originally I was only thinking about the IR LED, like the LED only light up few times a day, which wouldn't consume much juice... didn't take account of the web server running 24/7 via wifi lol, silly me.

However I was thinking about reducing the up time of web server, like only enable it at a certain time of day, or put it in an interval (3 mins up 3 mins down)... idk haha, I don't have electrical background so can't think of any workaround in terms of hardware.

**Comment by JZ-SmartThings** [comment]
Thank you sir! Honestly you're kinda screwed in that regard. I can't imagine any way of making this truly wireless unless you do a UPS type of solution. For instance my old U-Verse service came with a 12v UPS because I had phone with them and AT&T did that for customers with phone service in case of power outage. If you're anywhere around LA area, I ended up with two of them, happy to give you one. I also don't have service with them anymore so trying to figure out whether/if that smaller UPS can play a role in my HA projects. So far, no real use because no matter what, at some point that guy will need to be plugged in to recharge.

The power consumption will leave you with a week at best with the best Lithium Ion batteries. I think wiring more batteries in series will increase that time. The only other suggestion is to hack the fan itself and tap/source power from it but you don't want to do that for obvious reasons... after all your goal was not to mess up the fan hence the wireless/IR hack. The other option is to splice into the fan's cord for power. It's probably wiser to just use an extension cord :)

**Comment by casper-gh** [comment]
Yeah I wouldn't dare to open any electronic, I might get electrocuted myself haha.

I guess it has to be wired anyway, it shouldn't be a problem since all electronics from fan to tv must sit near an outlet and an extra cord wouldn't hurt.

Anyway thanks for the offer though, and hey I live in OC :)

**Comment by JZ-SmartThings** [comment]
Nice, neighbor :)
