### ISSUE TITLE
Triggers got triggered 3 times

### ISSUE THREAD

**Issue by casper-gh** [JZ-SmartThings/SmartThings#4]
Hey @JZ-SmartThings how you been?

Not sure if this happened to you but recently all my HTTP devices have been acting weird: the trigger got triggered 3 times instead of 1. So for example, my fan device, when I turn it on from Alexa/iOS app, my IR LED blinked 3 times, the fan eventually turn off but but signal is sent 3 times.

I've tested on the local web interface with no issue, so I assume the bug must come from ST. 

My best guess is ST updated the IDE which caused the problem? I haven't been following the forum so please excuse me if I missed that.

Thanks and have a great weekend.

**Comment by JZ-SmartThings** [comment]
Hey buddy, this is definitely not my bug since you obviously don't see a loop/re-attempt anywhere in my code. I've tried many times to reproduce but not able to... I would keep a close eye on your ST Log while executing the function. That should show the repeated logic, in theory. I'm surprised you're seeing the opposite of what I'm seeing. To my surprise, the LAN communication with ST has been much faster and a tiny bit more reliable after their last hub update on 5/9/2016. Their Android app and labels have gotten totally messed up (for which I had an on-going case with ST) but the functionality/execution has been much snappier.

All the best!

**Comment by casper-gh** [comment]
Aaaaaaaaaaaand it works, after rebooting the hub. I should've done this before making noise here hehe. 

Anyway thanks for validating.

**Comment by JZ-SmartThings** [comment]
Anytime! I've had issues like that too with image/camera processing and the hubAction command. The unreliability of an HA system like ST is pretty discouraging :(
